/* ==========================================================================
   Curitiba - Tourist Spot Data
   Consumed by ../assets/app.js
   ========================================================================== */

window.CITY_NAME = 'Balneário Camboriú';

window.CITY_DATA = [
{
  id: 'parque_unipraias',
  name: 'Parque Unipraias',
  category: 'Aventura',
  categoryClass: 'adventure',
  address: 'Av. Atlântica, 6006 - Barra Sul',
  hours: '09:30h às 17:30h (horário sujeito a alterações, consulte o site oficial)',
  price: 'Bondinho: R$ 80,00 (Meia: R$ 40,00)',
  rating: '4.7 ★ (milhares de avaliações)',
  popularRank: 1,
  route: 1,
  image: 'imagens/unipraias.jpg',
  summary: 'Complexo turístico que conecta Barra Sul, Mata Atlântica e Praia de Laranjeiras por meio de bondinhos aéreos.',
  description: 'O Parque Unipraias é um dos principais atrativos turísticos de Balneário Camboriú. Seus bondinhos aéreos interligam três estações: Barra Sul, Mata Atlântica e Laranjeiras. Durante o passeio, os visitantes podem apreciar vistas panorâmicas da cidade, do mar e da Mata Atlântica, além de acessar trilhas, mirantes e atrações opcionais como o Youhooo!, ZipRider e Fantástica Floresta.',
  tip: 'Reserve algumas horas para conhecer a Estação Mata Atlântica e programe o passeio em dias de céu aberto para aproveitar melhor as vistas panorâmicas.'
},
{
  id: 'molhe_barra_sul',
  name: 'Molhe da Barra Sul',
  category: 'Paisagem',
  categoryClass: 'nature',
  address: 'Av. Atlântica, s/n - Barra Sul',
  hours: 'Aberto 24 horas',
  price: 'Gratuito',
  rating: '4.8 ★ (milhares de avaliações)',
  popularRank: 2,
  route: 2,  
  image: 'imagens/molhe.jpg',
  summary: 'Extenso molhe à beira-mar com vista privilegiada para a Praia Central e a skyline de Balneário Camboriú.',
  description: 'Também conhecido como Pontal Klaus Fischer, o Molhe da Barra Sul possui aproximadamente 452 metros de extensão e está localizado em frente ao Parque Unipraias. O passeio é ideal para caminhadas, contemplação da orla e fotografias. Ao longo do percurso, há áreas de descanso e uma vista panorâmica da Praia Central.',
  tip: 'Visite no final da tarde ou à noite para aproveitar a iluminação do local e fotografar a cidade iluminada.'
},
{
  id: 'fg_big_wheel',
  name: 'Roda Gigante FG',
  category: 'Entretenimento',
  categoryClass: 'entertainment',
  address: 'Estrada da Rainha, 1009 - Pioneiros',
  hours: 'Consulte os horários atualizados no site oficial',
  price: 'Ingressos a partir de aproximadamente R$ 58,90',
  rating: '4.8 ★ (milhares de avaliações)',
  popularRank: 3,
  route: 7,
  image: 'imagens/roda.jpg',
  summary: 'Uma das maiores rodas-gigantes da América Latina, com vista panorâmica para o mar, a cidade e a Mata Atlântica.',
  description: 'A FG Big Wheel é um dos cartões-postais mais conhecidos de Balneário Camboriú. Com seu ponto mais alto a aproximadamente 82 metros acima do nível do mar, proporciona uma vista panorâmica de 360 graus da Praia Central, dos arranha-céus e da Mata Atlântica. O passeio dura cerca de 15 a 20 minutos e é realizado em cabines projetadas para proporcionar conforto aos visitantes.',
  tip: 'Para fotos incríveis, escolha um horário próximo ao pôr do sol, quando é possível observar a cidade durante a transição entre o dia e a noite.'
},
{
  id: 'big_bar_rooftop',
  name: 'Big Bär Rooftop',
  category: 'Gastronomia',
  categoryClass: 'food',
  address: 'Estrada da Rainha, 1009 - Pioneiros',
  hours: 'Segunda, quinta, sexta, sábado e domingo: 17h00 às 22h00',
  price: 'Consumo no local',
  rating: '4.7 ★ (avaliações online)',
  popularRank: 7,
  route: 8,
  image: 'imagens/big bar rooftop.jpg',
  summary: 'Rooftop gastronômico com ambiente sofisticado e vista privilegiada da região do Pontal Norte, anexo à icônica FG Big Wheel.',
  description: 'O Big Bär Rooftop é uma opção gastronômica localizada na região do Pontal Norte, próximo à FG Big Wheel. O espaço combina gastronomia, drinks e um ambiente elegante, oferecendo uma experiência diferenciada para quem deseja apreciar a noite de Balneário Camboriú em um local com vista para um dos principais cartões-postais da cidade.',
  tip: 'Faça reserva antecipadamente, especialmente em finais de semana e durante a alta temporada.'
},
{
  id: 'rua_torta',
  name: 'Rua Torta',
  category: 'Arquitetura',
  categoryClass: 'culture',
  address: 'Estr. da Rainha 1009 - Pioneiros',
  hours: 'Acesso livre',
  price: 'Gratuito',
  rating: 'Novo ponto turístico',
  popularRank: 8,
  route: 5,
  image: 'imagens/rua torta.jpg',
  summary: 'Ponto urbano com arquitetura e traçado visual diferenciados que se tornou uma curiosidade para visitantes e fotografias.',
  description: 'Conhecida popularmente como Rua Torta, a atração chama a atenção pelo seu aspecto urbano incomum e se tornou um ponto de curiosidade e registros fotográficos em Balneário Camboriú. É uma opção de passeio rápido, especialmente para visitantes que gostam de explorar locais diferentes e descobrir cenários urbanos fora dos roteiros tradicionais.',
  tip: 'Combine a visita com outros atrativos da região do Pontal Norte e da Avenida Atlântica para aproveitar melhor o passeio.'
},
{
  id: 'cristo_luz',
  name: 'Cristo Luz',
  category: 'Cultura',
  categoryClass: 'culture',
  address: 'Rua Indonésia, 800 - Nações',
  hours: 'Segunda a sábado: 16h00 às 00h',
  price: 'Consulte os valores atualizados de ingresso no site oficial',
  rating: '4.7 ★ (milhares de avaliações)',
  popularRank: 4,
  route: 9,
  image: 'imagens/cristo.jpg',
  summary: 'Monumento localizado em um dos pontos mais altos da cidade, com vista panorâmica de Balneário Camboriú e iluminação especial à noite.',
  description: 'O Cristo Luz é um dos símbolos mais conhecidos de Balneário Camboriú. Localizado no alto de um morro, o complexo oferece mirantes com vista panorâmica para a cidade, a Praia Central e o litoral. À noite, o monumento recebe uma iluminação especial com diferentes cores, criando um espetáculo visual que pode ser observado de vários pontos da cidade.',
  tip: 'Chegue próximo ao pôr do sol para apreciar a vista durante o dia e permaneça até o anoitecer para ver o espetáculo de iluminação do monumento.'
},
{
  id: 'deck_pontal_norte',
  name: 'Deck do Pontal Norte',
  category: 'Natureza',
  categoryClass: 'nature',
  address: 'Avenida Atlântica - Pioneiros',
  hours: 'Diariamente: 06h00 às 23h00',
  price: 'Gratuito',
  rating: '4.8 ★ (milhares de avaliações)',
  popularRank: 5,
  route: 6,
  image: 'imagens/deck.jpg',
  summary: 'Passarela panorâmica junto à Mata Atlântica, com mais de 800 metros de caminhada e belas vistas do litoral.',
  description: 'O Deck do Pontal Norte é uma das atrações mais procuradas por quem deseja caminhar próximo à natureza em Balneário Camboriú. A estrutura acompanha a encosta do Pontal Norte e proporciona vistas privilegiadas do mar, da Praia Central e da vegetação da Mata Atlântica. Após uma ampla revitalização, o espaço recebeu melhorias na estrutura, iluminação, mobiliário e paisagismo.',
  tip: 'Faça o passeio no início da manhã ou no final da tarde, quando as temperaturas são mais agradáveis e a iluminação é ideal para fotografias.'
},
{
  id: 'rua_guarda_chuvas',
  name: 'Rua dos Guarda-Chuvas Coloridos',
  category: 'Cultura',
  categoryClass: 'culture',
  address: 'R. 1200 - Centro',
  hours: 'Aberto 24 horas',
  price: 'Gratuito',
  rating: '4.8 ★ (463 avaliações)',
  popularRank: 9,
  route: 4,
  image: 'imagens/rua.png',
  summary: 'Charmoso corredor urbano decorado com dezenas de guarda-chuvas coloridos suspensos, formando um dos cenários mais fotogênicos da cidade.',
  description: 'A Rua dos Guarda-Chuvas Coloridos é uma atração urbana localizada na Rua 1200, no Centro de Balneário Camboriú. O local se destaca pela decoração composta por diversos guarda-chuvas coloridos suspensos sobre a rua, criando um túnel vibrante e instagramável. É um passeio rápido e gratuito, ideal para fotografias e para combinar com uma caminhada pelo comércio e outros atrativos do centro da cidade.',
  tip: 'Visite durante o dia para aproveitar melhor as cores dos guarda-chuvas nas fotografias e combine o passeio com uma visita aos atrativos próximos do Centro.'
},
{
  id: 'summit_bc',
  name: 'SUMMITBC',
  category: 'Entretenimento',
  categoryClass: 'entertainment',
  address: 'Av. Atlântica, 2554 - Cobertura do Edifício Imperatriz - Centro',
  hours: 'Segunda a sexta: 10h00 às 23h00 | Sábado e domingo: 09h00 às 23h00',
  price: 'Consulte os valores atualizados dos ingressos no site oficial',
  rating: '4.8 ★ (4.037 avaliações)',
  popularRank: 2,
  route: 3,
  image: 'imagens/summit.png',
  summary: 'Experiência panorâmica a 120 metros de altura com cubos de vidro suspensos, vista para Balneário Camboriú, gastronomia e atrações interativas.',
  description: 'O SUMMITBC é um dos mais novos pontos turísticos de Balneário Camboriú e oferece uma experiência panorâmica a aproximadamente 120 metros de altura. Seu principal destaque são os cubos de vidro suspensos, que proporcionam a sensação de estar flutuando sobre a cidade enquanto os visitantes observam a Praia Central, os arranha-céus, o Cristo Luz e outros cartões-postais da região. O complexo também conta com varanda panorâmica, experiências interativas, cafeteria e restaurante.',
  tip: 'Programe sua visita para o final da tarde. Assim, você poderá apreciar a vista durante o dia, acompanhar o pôr do sol e observar as luzes de Balneário Camboriú ao anoitecer.'
}
];
