/* ==========================================================================
   Florianópolis - Tourist Spot Data
   Consumed by ../assets/app.js
   ========================================================================== */

window.CITY_NAME = 'Florianópolis';

window.CITY_DATA = [
  {
    id: 'totem_floripa',
    name: 'Floripa Totem: #Floripa',
    category: 'Atração',
    city: 'Florianópolis',
    address: 'Av. Jorn. Rubéns de Arruda Ramos, 5438 - Beira-Mar Norte',
    hours: 'Acesso 24h',
    price: 'Gratuito',
    rating: '4.7 ★ (935 avaliações)',
    popularRank: 14,
    route: 1,
    image: 'imagens/totem_floripa.jpg',
    summary: 'Grande letreiro turístico na Beira-Mar Norte que se tornou um dos cenários mais fotografados de Florianópolis.',
    description: 'O Totem Floripa é um dos pontos preferidos dos visitantes para registrar a passagem pela Ilha da Magia. Localizado na região da Beira-Mar Norte, o letreiro proporciona um cenário urbano com a baía e a paisagem de Florianópolis ao fundo.',
    tip: 'Faça uma foto em frente ao letreiro e aproveite para caminhar pela Avenida Beira-Mar Norte.'
  },
  {
    id: 'soubem_floripa',
    name: 'SouBem Floripa',
    category: 'Atração',
    city: 'Florianópolis',
    address: 'Av. Jorn. Rubens Arruda Ramos - Beira-Mar Norte',
    hours: 'Acesso 24h',
    price: 'Gratuito',
    rating: '4.7 ★ (52 avaliações)',
    popularRank: 23,
    route: 2,
    image: 'imagens/soubem_floripa.jpg',
    summary: 'Totem fotográfico que integra o movimento Sou Bem Floripa e se tornou um símbolo turístico da cidade.',
    description: 'O movimento Sou Bem Floripa foi criado para incentivar pequenas atitudes de cidadania, convivência e cuidado com a cidade. Seus grandes totens com a mensagem “Sou Bem Floripa” passaram a ser utilizados pelos visitantes como cenários para fotografias. Entre os locais onde já foram instalados estão a Beira-Mar Norte, o Mirante do Morro da Lagoa, o Parque de Coqueiros e no Parque da Luz (próximo à Ponte Hercílio Luz).',
    tip: 'Procure visitar em horários de menor movimento, quando fica mais fácil conseguir uma foto sem muitas pessoas ao redor.'
  },
  {
    id: 'cafe_manha_kattamaram',
    name: 'Kattamaram - Café da Manhã',
    category: 'Entretenimento',
    city: 'Florianópolis',
    address: 'Trapiche - Beira-Mar Norte',
    hours: 'Quarta a domingo: 08h às 10h | Horários sujeitos a alterações, consulte o site oficial',
    price: 'Consultar valor',
    rating: '5.0 ★ (9 avaliações)',
    popularRank: 24,
    route: 3,
    image: 'imagens/cafe_kattamaram.jpeg',
    summary: 'Experiência de café da manhã a bordo do Kattamaram IV, com a embarcação atracada e vista privilegiada para a Baía Norte.',
    description: 'O Café da Manhã do Kattamaram é uma experiência gastronômica diferente em Florianópolis. A embarcação permanece atracada no Trapiche da Beira-Mar Norte enquanto os visitantes desfrutam de um buffet de café da manhã com vista para a baía e para a paisagem da cidade. A experiência normalmente ocorre das 08h às 10h.',
    tip: 'Reserve antecipadamente, principalmente em finais de semana e datas especiais. O café da manhã é servido com a embarcação atracada.'
  },
  {
    id: 'forte_santana',
    name: 'Forte de Santana',
    category: 'Paisagem',
    city: 'Florianópolis',
    address: 'Av. Osvaldo Rodrigues Cabral (Av. Beira-Mar Norte) - Beira-Mar Norte',
    hours: 'Diariamente: 09h às 17h',
    price: 'Gratuito',
    rating: '4.7 ★ (232 avaliações)',
    popularRank: 13,
    route: 4,
    image: 'imagens/forte_santana.jpg',
    summary: 'Fortificação histórica construída no século XVIII, localizada aos pés da Ponte Hercílio Luz.',
    description: 'Construído em 1761, o Forte de Santana fazia parte do sistema defensivo da antiga Vila de Nossa Senhora do Desterro. Atualmente, o local preserva estruturas históricas e proporciona uma interessante vista das baías Norte e Sul, além de estar diretamente ligado à história militar de Florianópolis.',
    tip: 'Combine a visita ao forte com o Parque da Luz e a Ponte Hercílio Luz, que ficam próximos.'
  },
  {
    id: 'cabeçeira_ponte_hercilio_luz',
    name: 'Largo da Ponte Hercílio Luz',
    category: 'Paisagem',
    city: 'Florianópolis',
    address: 'R. Dg - Pte. Hercílio Luz, 606 - Centro',
    hours: 'Acesso 24h',
    price: 'Gratuito',
    rating: '4.7 ★',
    popularRank: 1,
    route: 5,
    image: 'imagens/parque_da_luz_ponte.png',
    summary: 'Área junto à cabeceira da Ponte Hercílio Luz, com mirantes e belas vistas para o principal cartão-postal de Florianópolis.',
    description: 'A Ponte Hercílio Luz é um dos principais símbolos de Florianópolis e uma das pontes suspensas mais marcantes do Brasil, conecta a Ilha de Santa Catarina ao continente e encanta pela grandiosidade de sua estrutura e pelas belas paisagens da Baía Norte.',
    tip: 'Visite no final da tarde para fotografar a ponte durante o pôr do sol e permanecer até o início da iluminação noturna.'
  },
  {
    id: 'mercado_publico_florianopolis',
    name: 'Mercado Público Municipal',
    category: 'Compras',
    city: 'Florianópolis',
    address: 'R. Jerônimo Coelho, 60 - Centro',
    hours: 'Consultar site oficial',
    price: 'Gratuito',
    rating: '4.5 ★ (97k+ avaliações)',
    popularRank: 2,
    route: 6,
    image: 'imagens/mercado_publico_floripa.jpg',
    summary: 'Tradicional centro gastronômico e cultural de Florianópolis, com restaurantes, bares, lojas, artesanato e produtos regionais.',
    description: 'O Mercado Público de Florianópolis é um dos principais pontos turísticos do centro histórico. Instalado em um prédio histórico com mais de um século, reúne restaurantes, bares, peixarias, lojas, artesanato e produtos típicos. É um dos melhores lugares para experimentar sabores tradicionais da Ilha, como frutos do mar e pastel de camarão.',
    tip: 'Reserve um tempo para conhecer o vão central e experimentar pratos à base de frutos do mar em um dos restaurantes.'
  },
  {
    id: 'casa_da_alfandega',
    name: 'Casa da Alfândega',
    category: 'Compras',
    city: 'Florianópolis',
    address: 'Largo da Alfândega - Centro',
    hours: 'Seg a Sex: 09h às 19h | Sáb: 09h às 13h | Dom: fechado',
    price: 'Gratuito',
    rating: '4.3 ★ (367 avaliações)',
    popularRank: 22,
    route: 7,
    image: 'imagens/casa_alfandega.png',
    summary: 'Edifício histórico em estilo neoclássico que atualmente abriga a Galeria do Artesanato Catarinense.',
    description: 'Inaugurada em 1876, a Casa da Alfândega é um dos edifícios históricos mais importantes do centro de Florianópolis. O prédio funcionou como alfândega durante décadas e atualmente abriga a Galeria do Artesanato, onde são comercializadas peças produzidas por artesãos de diferentes regiões de Santa Catarina.',
    tip: 'Aproveite a visita para conhecer o artesanato catarinense e depois caminhe pelo Largo da Alfândega até o Mercado Público.'
  },
  {
    id: 'catedral_metropolitana',
    name: 'Catedral Metropolitana',
    category: 'Atração',
    city: 'Florianópolis',
    address: 'R. Padre Miguelinho, 55 - Centro',
    hours: 'Seg a Sex: 09h às 17h | Sáb: 09h às 11h | Dom: conforme programação religiosa',
    price: 'Gratuito',
    rating: '4.8 ★ (2.9k avaliações)',
    popularRank: 9,
    route: 8,
    image: 'imagens/catedral_floripa.jpeg',
    summary: 'Importante templo religioso e patrimônio histórico localizado no coração do centro de Florianópolis.',
    description: 'A Catedral Metropolitana de Florianópolis, dedicada a Nossa Senhora do Desterro e Santa Catarina de Alexandria, é um dos principais marcos religiosos e arquitetônicos da capital catarinense. Localizada junto à Praça XV, integra o conjunto histórico mais importante do centro da cidade.',
    tip: 'Combine a visita com a Praça XV, o Palácio Cruz e Sousa e o centro histórico.'
  },
  {
    id: 'praca_xv_florianopolis',
    name: 'Praça XV de Novembro',
    category: 'Atração',
    city: 'Florianópolis',
    address: 'Praça XV de Novembro, s/n - Centro',
    hours: 'Acesso 24h',
    price: 'Gratuito',
    rating: '4.0 ★ (673 avaliações)',
    popularRank: 8,
    route: 9,
    image: 'imagens/praca_xv_floripa.png',
    summary: 'Uma das praças mais tradicionais de Florianópolis, cercada por edifícios históricos e pela famosa figueira centenária.',
    description: 'A Praça XV de Novembro é um dos principais espaços históricos de Florianópolis. Localizada no coração do centro, reúne árvores, jardins e monumentos e é marcada pela presença da tradicional figueira centenária. Ao seu redor estão atrações como a Catedral Metropolitana e o Palácio Cruz e Sousa.',
    tip: 'Caminhe ao redor da praça e observe a grande figueira, um dos símbolos mais tradicionais do centro de Florianópolis.'
  },
  {
    id: 'praia_jurere_internacional',
    name: 'Praia de Jurerê Internacional',
    category: 'Natureza',
    city: 'Florianópolis',
    address: 'Jurerê Internacional',
    hours: 'Acesso 24h',
    price: 'Gratuito',
    rating: '4.7 ★ (849 avaliações)',
    popularRank: 4,
    route: 10,
    image: 'imagens/jurere_internacional.png',
    summary: 'Praia de águas calmas e infraestrutura sofisticada, conhecida pelos beach clubs, e pelo ambiente de alto padrão.',
    description: 'Jurerê Internacional é um dos destinos mais conhecidos do litoral de Florianópolis. A praia possui águas geralmente calmas e uma extensa faixa de areia, enquanto o bairro oferece hotéis, restaurantes, beach clubs e infraestrutura voltada ao turismo. A região é especialmente movimentada durante o verão.',
    tip: 'Durante a alta temporada, chegue cedo para encontrar estacionamento e aproveitar a praia com mais tranquilidade.'
  },
  {
    id: 'pitangueiras_sambaqui',
    name: 'Pitangueiras Restaurante',
    category: 'Gastronomia',
    city: 'Florianópolis',
    address: 'Rod. Rafael da Rocha Pires, 2861 - Sambaqui',
    hours: 'Qui à Sáb: 11:30h às 23:30h | Dom, Seg e Qua: 11:30h às 17:00h |  Ter: Fechado',
    price: '$$ - $$$',
    rating: '4.5 ★ (3.3k+ avaliações)',
    popularRank: 19,
    route: 11,
    image: 'imagens/pitangueiras.jpg',
    summary: 'Restaurante à beira-mar em Sambaqui, conhecido pelos frutos do mar, ambiente acolhedor e belas vistas da Baía Norte.',
    description: 'Localizado na Ponta de Sambaqui, o Restaurante Pitangueiras oferece uma experiência gastronômica privilegiada junto ao mar. O cardápio valoriza peixes, ostras, camarões e outros frutos do mar, além de petiscos e bebidas. O restaurante possui ambiente interno envidraçado e deck de madeira à beira-mar, proporcionando uma vista especial da Baía Norte e um cenário especialmente agradável para apreciar o pôr do sol.',
    tip: 'Prefira os horários próximos ao pôr do sol para aproveitar a vista privilegiada do mar enquanto saboreia os pratos da casa.'
  },
  {
    id: 'freguesia_santo_antonio_lisboa',
    name: 'Santo Antônio de Lisboa',
    category: 'Natureza',
    city: 'Florianópolis',
    address: 'R. Quinze de Novembro, 147 - Santo A. de Lisboa',
    hours: 'Acesso 24h',
    price: 'Gratuito',
    rating: '4.7 ★',
    popularRank: 7,
    route: 12,
    image: 'imagens/santo_antonio_lisboa.jpg',
    summary: 'Uma das comunidades mais antigas de Florianópolis, conhecida pelo casario açoriano, artesanato e pôr do sol.',
    description: 'Santo Antônio de Lisboa preserva uma das mais importantes paisagens culturais de Florianópolis, marcada pela arquitetura colonial e pela forte influência açoriana. A região possui restaurantes especializados em frutos do mar e ostras, ateliês, artesanato e uma orla tranquila com belas vistas da Baía Norte.',
    tip: 'Chegue no final da tarde para caminhar pela orla e apreciar o famoso pôr do sol de Santo Antônio de Lisboa.'
  },
  {
    id: 'fairyland_santo_antonio',
    name: 'FairyLand - Santo Antônio de Lisboa',
    category: 'Gastronomia',
    city: 'Florianópolis',
    address: 'Estrada Caminho dos Açores, 1740 - Santo A. de Lisboa',
    hours: 'Diariamente: 13h às 20h',
    price: '$ - $$',
    rating: '4.6 ★ (3.2k+ avaliações)',
    popularRank: 21,
    route: 13,
    image: 'imagens/fairyland.jpg',
    summary: 'Café e confeitaria com ambiente encantador, especializado em bolos, tortas e cupcakes em Santo Antônio de Lisboa.',
    description: 'A FairyLand Santo Antônio de Lisboa é uma charmosa confeitaria localizada no Caminho dos Açores, em uma das regiões mais tradicionais de Florianópolis. A casa aposta em uma atmosfera lúdica e acolhedora e oferece bolos, tortas, cupcakes e outras sobremesas. O espaço é uma opção agradável para fazer uma pausa durante o passeio por Santo Antônio de Lisboa e conhecer a gastronomia da região.',
    tip: 'Inclua a FairyLand no passeio por Santo Antônio de Lisboa e aproveite para conhecer as construções históricas e a orla do bairro.'
  },
  {
    id: 'praia_cacupe',
    name: 'Praia de Cacupé',
    category: 'Natureza',
    city: 'Florianópolis',
    address: 'Estrada Haroldo Soares Glavan, 2003-1941 - Cacupé',
    hours: 'Acesso 24h',
    price: 'Gratuito',
    rating: '4.6 ★ (248 avaliações)',
    popularRank: 15,
    route: 14,
    image: 'imagens/praia_cacupe.jpg',
    summary: 'Praia tranquila de águas calmas na Baía Norte, com vista para o centro de Florianópolis e para as pontes da cidade.',
    description: 'A Praia de Cacupé possui aproximadamente 650 metros de extensão e apresenta águas tranquilas, características de uma praia de baía. Cercada por vegetação e com vista para o centro de Florianópolis e para o continente, é uma opção interessante para quem busca tranquilidade e belas paisagens.',
    tip: 'Combine Cacupé com Santo Antônio de Lisboa, principalmente no final da tarde para apreciar o pôr do sol.'
  },
  {
    id: 'morro_lagoa_conceicao',
    name: 'Morro da Lagoa da Conceição',
    category: 'Paisagem',
    city: 'Florianópolis',
    address: 'Rodovia Admar Gonzaga - Lagoa da Conceição',
    hours: 'Acesso 24h',
    price: 'Gratuito',
    rating: '4.8 ★ (18k+ avaliações)',
    popularRank: 6,
    route: 15,
    image: 'imagens/morro_lagoa_conceicao.jpg',
    summary: 'Mirante na subida do Morro da Lagoa, com vista panorâmica para a Lagoa da Conceição e parte da Ilha de Santa Catarina.',
    description: 'O Mirante do Morro da Lagoa da Conceição é uma das paradas mais tradicionais para contemplar a paisagem de Florianópolis. Do alto é possível observar a Lagoa da Conceição, os morros, áreas urbanizadas e diferentes regiões da Ilha de Santa Catarina.',
    tip: 'Pare no mirante durante o trajeto entre o centro e a Lagoa da Conceição e aproveite para registrar uma fotografia panorâmica.'
  },
  {
    id: 'praia_joaquina',
    name: 'Praia da Joaquina',
    category: 'Natureza',
    city: 'Florianópolis',
    address: 'Av. Pref. Acácio Garibaldi São Thiago, s/n - Joaquina',
    hours: 'Acesso 24h',
    price: 'Gratuito',
    rating: '4.7 ★ (31.3k avaliações)',
    popularRank: 3,
    route: 16,
    image: 'imagens/praia_joaquina.jpg',
    summary: 'Uma das praias mais famosas de Florianópolis, conhecida pelas ondas, pelo surfe, pelas dunas e pelo nascer do sol.',
    description: 'A Praia da Joaquina possui cerca de 3 quilômetros de extensão e é reconhecida internacionalmente por suas condições favoráveis ao surfe. Além da praia, a região possui grandes dunas utilizadas para sandboard e áreas de interesse arqueológico nas proximidades.',
    tip: 'Chegue cedo para assistir ao nascer do sol e, se gostar de aventura, experimente o sandboard nas dunas.'
  },
  {
    id: 'praia_campeche',
    name: 'Praia do Campeche',
    category: 'Natureza',
    city: 'Florianópolis',
    address: 'Avenida Pequeno Príncipe - Campeche',
    hours: 'Acesso 24h',
    price: 'Gratuito',
    rating: '4.7 ★ (9.2k avaliações)',
    popularRank: 5,
    route: 17,
    image: 'imagens/praia_campeche.png',
    summary: 'Procurada por surfistas, praticantes de kitesurfe e visitantes que desejam conhecer a Ilha do Campeche.',
    description: 'A Praia do Campeche possui aproximadamente 3,5 quilômetros de extensão e combina faixa de areia, mar aberto e paisagens naturais. É bastante procurada para esportes aquáticos e também funciona como um dos principais pontos de embarque para a Ilha do Campeche.',
    tip: 'Se quiser visitar a Ilha do Campeche, reserve o passeio com antecedência e confira as condições de navegação.'
  },
  {
  id: 'mirante_vila_fatima',
  name: 'Mirante Vila Fátima',
  category: 'Paisagem',
  city: 'Florianópolis',
  address: 'Rodovia Francisco Thomaz dos Santos, SC-406, 2210 - Morro das Pedras',
  hours: 'Geralmente: 09h às 18h',
  price: 'Gratuito',
  rating: '4.8 ★ (3.1k avaliações)',
  popularRank: 12,
  route: 18,
  image: 'imagens/mirante_vila_fatima.jpg',
  summary: 'Mirante localizado no alto do Morro das Pedras, com uma vista panorâmica privilegiada para a Praia da Armação, o litoral sul de Florianópolis e áreas naturais da região.',
  description: 'O Mirante Vila Fátima está situado junto à Casa de Retiros Vila Fátima, no Morro das Pedras, em uma área cercada pela Mata Atlântica. Do alto, é possível contemplar a Praia da Armação, o Morro das Pedras, a Praia do Matadeiro e parte da Lagoa do Peri, formando um cenário especialmente bonito para fotografias e contemplação. O local também é conhecido como Mirante do Morro das Pedras ou Mirante da Praia da Armação.',
  tip: 'Visite em dias de céu aberto para aproveitar melhor a vista e, entre junho e novembro, fique atento à possibilidade de avistar baleias-francas no litoral. Por estar junto a uma casa de retiros, mantenha o silêncio e respeite o ambiente.'
  },  
  {
    id: 'mirante_morro_das_pedras',
    name: 'Mirante do Morro das Pedras',
    category: 'Paisagem',
    city: 'Florianópolis',
    address: 'Rod. Francisco Thomaz dos Santos, 2210 - Morro das Pedras',
    hours: 'Acesso 24h',
    price: 'Gratuito',
    rating: '4.8 ★ (4.6k avaliações)',
    popularRank: 11,
    route: 19,
    image: 'imagens/mirante_morro_das_pedras.jpg',
    summary: 'Mirante com vista panorâmica para o litoral sul de Florianópolis, especialmente para as Praias do Morro das Pedras e Campeche.',
    description: 'O Mirante do Morro das Pedras proporciona uma das paisagens mais bonitas do sul da Ilha de Santa Catarina. O visitante pode observar a faixa litorânea, o mar aberto, criando um cenário ideal para contemplação e fotografia.',
    tip: 'Visite em dias de céu limpo e aproveite o percurso para conhecer também a Praia do Morro das Pedras e a Lagoa do Peri.'
  },
  {
    id: 'ribeirao_da_ilha',
    name: 'Ribeirão da Ilha - Freguesia',
    category: 'Natureza',
    city: 'Florianópolis',
    address: 'Rod. Baldicero Filomeno - Ribeirão da Ilha',
    hours: 'Acesso 24h',
    price: 'Gratuito',
    rating: '4.8 ★ (1.3k avaliações)',
    popularRank: 10,
    route: 20,
    image: 'imagens/ribeirao_da_ilha.jpg',
    summary: 'Histórico distrito açoriano conhecido pelo casario tradicional, pela produção de ostras e pela gastronomia à base de frutos do mar.',
    description: 'Ribeirão da Ilha é uma das regiões mais tradicionais de Florianópolis e preserva fortes características da colonização açoriana. O distrito combina casario histórico, igrejas, praias tranquilas, restaurantes especializados em frutos do mar e uma das principais áreas produtoras de ostras do Brasil.',
    tip: 'Reserve algumas horas para conhecer o centro histórico e experimentar ostras frescas em um dos restaurantes da região.'
  },
  {
    id: 'rancho_acoriano_ribeirao',
    name: 'Rancho Açoriano - Ribeirão da Ilha',
    category: 'Gastronomia',
    city: 'Florianópolis',
    address: 'Rod. Baldicero Filomeno, 5634 - Ribeirão da Ilha',
    hours: 'Seg a Sáb: 11h às 23h | Dom: 11h às 16h',
    price: '$$ - $$$',
    rating: '4.8 ★ (4.0k avaliações)',
    popularRank: 18,
    route: 21,
    image: 'imagens/rancho-acoriano.png',
    summary: 'Tradicional restaurante de frutos do mar que valoriza a gastronomia açoriana e as raízes do Ribeirão da Ilha.',
    description: 'Fundado em 1997 no Ribeirão da Ilha, o Rancho Açoriano é referência na gastronomia de frutos do mar em Florianópolis. O restaurante preserva a tradição açoriana e destaca ingredientes frescos, incluindo ostras, pescados e camarões. Entre os pratos conhecidos da casa estão as ostras gratinadas, a moqueca e o camarão tropical. O ambiente combina boa gastronomia, hospitalidade e a atmosfera histórica de uma das comunidades mais tradicionais da Ilha.',
    tip: 'Experimente as ostras gratinadas e outros pratos de frutos do mar, aproveitando para conhecer o histórico Ribeirão da Ilha.'
  },
  {
    id: 'praia_itaguacu',
    name: 'Praia de Itaguaçu',
    category: 'Natureza',
    city: 'Florianópolis',
    address: 'Itaguaçu',
    hours: 'Acesso 24h',
    price: 'Gratuito',
    rating: '4.8 ★ (346 avaliações)',
    popularRank: 16,
    route: 22,
    image: 'imagens/praia_itaguacu.jpg',
    summary: 'Praia tranquila da região continental de Florianópolis, cercada por formações rochosas e com belas vistas para a Baía Sul.',
    description: 'A Praia de Itaguaçu está localizada no bairro de Coqueiros e é conhecida pela paisagem formada por pequenas ilhas e rochas que surgem nas águas da baía. A região possui restaurantes, bares e espaços para contemplação, sendo uma opção agradável para um passeio no continente.',
    tip: 'Combine Itaguaçu com a Praia de Bom Abrigo e o Parque de Coqueiros para fazer um roteiro pela região continental.'
  },
  {
    id: 'entre_cortes_itaguacu',
    name: 'Entre Cortes Floripa - Itaguaçu',
    category: 'Gastronomia',
    city: 'Florianópolis',
    address: 'R. Doná Antônia Alves, 59 - Itaguaçu',
    hours: 'Seg a Qui: 11:30h às 15h e 18:30h às 23:30h | Sex e Sáb: 11:30h às 23:30h | Dom e feriados: 11:30h às 16h e 18:30h às 23:30h',
    price: '$$ - $$$',
    rating: '4.9 ★ (1.3k+ avaliações)',
    popularRank: 20,
    route: 23,
    image: 'imagens/entre-cortes.jpg',
    summary: 'Restaurante frente ao mar especializado em cortes premium, carnes, frutos do mar, massas e pizza napolitana.',
    description: 'Localizado na região gastronômica de Itaguaçu, o Entre Cortes Floripa combina restaurante, grill, enoteca e pizzaria em um ambiente com vista para o mar. O cardápio reúne cortes premium, frutos do mar preparados na brasa, massas artesanais e pizzas napolitanas. A casa também conta com uma seleção de vinhos e atendimento voltado para experiências gastronômicas especiais.',
    tip: 'Para uma experiência completa, combine um dos cortes da casa com um vinho selecionado pela enoteca.'
  },
  {
    id: 'praia_bom_abrigo',
    name: 'Praia de Bom Abrigo',
    category: 'Natureza',
    city: 'Florianópolis',
    address: 'Bom Abrigo',
    hours: 'Acesso 24h',
    price: 'Gratuito',
    rating: '4.8 ★ (234 avaliações)',
    popularRank: 17,
    route: 24,
    image: 'imagens/praia_bom_abrigo.jpg',
    summary: 'Pequena praia de águas tranquilas localizada na região continental de Florianópolis, próxima a Praia de Itaguaçú.',
    description: 'A Praia de Bom Abrigo é uma das praias mais tranquilas da região continental de Florianópolis. Protegida pelas águas da Baía Sul, apresenta ambiente agradável para contemplação e lazer e está próxima de outras atrações de Coqueiros e Itaguaçu.',
    tip: 'Aproveite para caminhar pela orla e conhecer os restaurantes da região de Coqueiros.'
  },
  {
    id: 'forneria_catarina_kplatz',
    name: 'Forneria Catarina - K-Platz',
    category: 'Gastronomia',
    city: 'São José',
    address: 'Av. Presidente Kennedy, 568 - Salas 01 e 06 - São José',
    hours: 'Diariamente: 18:00h às 23:50h',
    price: '$$ - $$$',
    rating: '4.8 ★ (2.3k+ avaliações)',
    popularRank: 25,
    route: 25,
    image: 'imagens/forneria-catarina.jpg',
    summary: 'Pizzaria artesanal conhecida pelas pizzas de inspiração paulistana, com massa leve e borda aerada e crocante.',
    description: 'A Forneria Catarina, localizada no complexo K-Platz, em São José, é uma pizzaria especializada em pizzas artesanais preparadas em forno de alta temperatura. Inspirada nas tradicionais pizzarias paulistanas, a casa se destaca pela massa leve, aerada e pela borda crocante. O ambiente contemporâneo é adequado para refeições com a família ou amigos.',
    tip: 'Experimente uma das pizzas artesanais da casa e aproveite para conhecer as demais opções gastronômicas do K-Platz.'
  },
  {
    id: 'di_panna_kplatz',
    name: 'Di Panna - K-Platz',
    category: 'Gastronomia',
    city: 'São José',
    address: 'R. Elizeu di Bernardi, 50 - São José',
    hours: 'Seg a Sáb: 11:30h às 23h | Dom: 11:30h às 22:00h',
    price: '$ - $$',
    rating: '4.9 ★ (418 avaliações)',
    popularRank: 26,
    route: 26,
    image: 'imagens/di-panna.jpg',
    summary: 'Gelateria localizada no K-Platz Markt, ideal para uma pausa com sobremesas geladas em meio ao polo gastronômico de São José.',
    description: 'A Di Panna é uma gelateria localizada no K-Platz Markt, em Campinas, São José. O estabelecimento integra o complexo gastronômico que reúne diferentes restaurantes, bares e opções de alimentação. É uma alternativa para quem deseja fazer uma pausa durante o passeio e aproveitar sobremesas geladas em um ambiente descontraído e movimentado.',
    tip: 'Combine a visita à Di Panna com um passeio pelo K-Platz Markt, que reúne diversas opções gastronômicas no mesmo complexo.'
  }
];
