/* ==========================================================================
   Florianópolis - Tourist Spot Data
   Consumed by ../assets/app.js
   ========================================================================== */

window.CITY_NAME = 'Florianópolis';

window.CITY_DATA = [
  {
    id: 'totem_floripa',
    name: 'Totem Floripa',
    category: 'Atração',
    city: 'Florianópolis',
    address: 'Av. Jorn. Rubéns de Arruda Ramos, 5438 - Centro, Florianópolis - SC',
    hours: 'Diariamente: acesso livre',
    price: 'Gratuito',
    rating: '4.7 ★ (935 avaliações)',
    popularRank: 1,
    route: 1,
    image: 'imagens/totem_floripa.jpeg',
    summary: 'Grande letreiro turístico que se tornou um dos cenários mais fotografados de Florianópolis.',
    description: 'O Totem Floripa é um dos pontos preferidos dos visitantes para registrar a passagem pela Ilha da Magia. Localizado na região da Beira-Mar Norte, o letreiro proporciona um cenário urbano com a baía e a paisagem de Florianópolis ao fundo.',
    tip: 'Faça uma foto em frente ao letreiro e aproveite para caminhar pela Avenida Beira-Mar Norte.'
  },
  {
    id: 'soubem_floripa',
    name: 'SouBem Floripa',
    category: 'Atração',
    city: 'Florianópolis',
    address: 'Centro e outros pontos turísticos de Florianópolis - SC',
    hours: 'Diariamente: acesso livre',
    price: 'Gratuito',
    rating: '4.9 ★',
    popularRank: 2,
    route: 2,
    image: 'imagens/soubem_floripa.jpeg',
    summary: 'Totem fotográfico que integra o movimento Sou Bem Floripa e se tornou um símbolo turístico da cidade.',
    description: 'O movimento Sou Bem Floripa foi criado para incentivar pequenas atitudes de cidadania, convivência e cuidado com a cidade. Seus grandes totens com a mensagem “Sou Bem Floripa” passaram a ser utilizados pelos visitantes como cenários para fotografias. Entre os locais onde já foram instalados estão a Beira-Mar Norte, o Mirante do Morro da Lagoa e o Parque de Coqueiros.',
    tip: 'Confira a localização atual do totem antes de montar seu roteiro, pois ele já foi instalado em diferentes pontos da cidade.'
  },
  {
    id: 'cafe_manha_kattamaram',
    name: 'Café da Manhã Kattamaram',
    category: 'Gastronomia',
    city: 'Florianópolis',
    address: 'Trapiche Beira-Mar Norte - Largo da Avenida Beira-Mar, Centro, Florianópolis - SC',
    hours: 'Terça a domingo: 08:00h às 10:00h',
    price: 'Consultar valor do ingresso',
    rating: '5.0 ★',
    popularRank: 3,
    route: 3,
    image: 'imagens/cafe_kattamaram.jpeg',
    summary: 'Experiência de café da manhã a bordo do Kattamaram IV, com a embarcação atracada e vista privilegiada para a Baía Norte.',
    description: 'O Café da Manhã do Kattamaram é uma experiência gastronômica diferente em Florianópolis. A embarcação permanece atracada no Trapiche da Beira-Mar Norte enquanto os visitantes desfrutam de um buffet de café da manhã com vista para a baía e para a paisagem da cidade. A experiência normalmente ocorre das 08h às 10h.',
    tip: 'Reserve antecipadamente, principalmente em finais de semana e datas especiais. O café da manhã é servido com a embarcação atracada.'
  },
  {
    id: 'forte_santana',
    name: 'Forte de Santana',
    category: 'Cultura',
    city: 'Florianópolis',
    address: 'R. Ten. Silveira, 60 - Centro, Florianópolis - SC',
    hours: 'Diariamente: 09:00h às 17:00h',
    price: 'Gratuito',
    rating: '4.7 ★ (232 avaliações)',
    popularRank: 4,
    route: 4,
    image: 'imagens/forte_santana.jpg',
    summary: 'Fortificação histórica construída no século XVIII, localizada aos pés da Ponte Hercílio Luz.',
    description: 'Construído em 1761, o Forte de Santana fazia parte do sistema defensivo da antiga Vila de Nossa Senhora do Desterro. Atualmente, o local preserva estruturas históricas e proporciona uma interessante vista das baías Norte e Sul, além de estar diretamente ligado à história militar de Florianópolis.',
    tip: 'Combine a visita ao forte com o Parque da Luz e a Ponte Hercílio Luz, que ficam próximos.'
  },
  {
    id: 'cabeçeira_ponte_hercilio_luz',
    name: 'Ponte Hercílio Luz - Parque da Luz',
    category: 'Atração',
    city: 'Florianópolis',
    address: 'R. Felipe Schmidt - Centro, Florianópolis - SC',
    hours: 'Diariamente: acesso livre',
    price: 'Gratuito',
    rating: '4.7 ★',
    popularRank: 5,
    route: 5,
    image: 'imagens/parque_da_luz_ponte.png',
    summary: 'Área verde junto à cabeceira da Ponte Hercílio Luz, com mirantes e belas vistas para o principal cartão-postal de Florianópolis.',
    description: 'O Parque da Luz ocupa uma área de aproximadamente 37 mil m² na região central de Florianópolis. O parque possui áreas verdes, caminhos para pedestres, ciclovia, equipamentos de lazer e um mirante com vista privilegiada para a Ponte Hercílio Luz e a orla marítima.',
    tip: 'Visite no final da tarde para fotografar a ponte durante o pôr do sol e permanecer até o início da iluminação noturna.'
  },
  {
    id: 'mercado_publico_florianopolis',
    name: 'Mercado Público Municipal',
    category: 'Gastronomia',
    city: 'Florianópolis',
    address: 'R. Jerônimo Coelho, 60 - Centro, Florianópolis - SC',
    hours: 'Seg a Qui: 07:00h às 22:00h | Sex: 07:00h às 22:00h | Sáb e Dom: 07:00h às 17:00h',
    price: 'Gratuito',
    rating: '4.5 ★ (97k+ avaliações)',
    popularRank: 6,
    route: 6,
    image: 'imagens/mercado_publico_floripa.jpeg',
    summary: 'Tradicional centro gastronômico e cultural de Florianópolis, com restaurantes, bares, lojas, artesanato e produtos regionais.',
    description: 'O Mercado Público de Florianópolis é um dos principais pontos turísticos do centro histórico. Instalado em um prédio histórico com mais de um século, reúne restaurantes, bares, peixarias, lojas, artesanato e produtos típicos. É um dos melhores lugares para experimentar sabores tradicionais da Ilha, como frutos do mar e pastel de camarão.',
    tip: 'Reserve um tempo para conhecer o vão central e experimentar pratos à base de frutos do mar em um dos restaurantes.'
  },
  {
    id: 'casa_da_alfandega',
    name: 'Casa da Alfândega',
    category: 'Cultura',
    city: 'Florianópolis',
    address: 'Largo da Alfândega - Centro, Florianópolis - SC',
    hours: 'Seg a Sex: 09:00h às 19:00h | Sáb: 09:00h às 13:00h | Dom: fechado',
    price: 'Gratuito',
    rating: '4.3 ★ (367 avaliações)',
    popularRank: 7,
    route: 7,
    image: 'imagens/casa_alfandega.png',
    summary: 'Edifício histórico em estilo neoclássico que atualmente abriga a Galeria do Artesanato Catarinense.',
    description: 'Inaugurada em 1876, a Casa da Alfândega é um dos edifícios históricos mais importantes do centro de Florianópolis. O prédio funcionou como alfândega durante décadas e atualmente abriga a Galeria do Artesanato, onde são comercializadas peças produzidas por artesãos de diferentes regiões de Santa Catarina.',
    tip: 'Aproveite a visita para conhecer o artesanato catarinense e depois caminhe pelo Largo da Alfândega até o Mercado Público.'
  },
  {
    id: 'catedral_metropolitana',
    name: 'Catedral Metropolitana',
    category: 'Cultura',
    city: 'Florianópolis',
    address: 'R. Padre Miguelinho, 55 - Centro, Florianópolis - SC',
    hours: 'Seg a Sex: 09:00h às 17:00h | Sáb: 09:00h às 11:00h | Dom: conforme programação religiosa',
    price: 'Gratuito',
    rating: '4.7 ★ (2.9k avaliações)',
    popularRank: 8,
    route: 8,
    image: 'imagens/catedral_floripa.jpeg',
    summary: 'Importante templo religioso e patrimônio histórico localizado no coração do centro de Florianópolis.',
    description: 'A Catedral Metropolitana de Florianópolis, dedicada a Nossa Senhora do Desterro e Santa Catarina de Alexandria, é um dos principais marcos religiosos e arquitetônicos da capital catarinense. Localizada junto à Praça XV, integra o conjunto histórico mais importante do centro da cidade.',
    tip: 'Combine a visita com a Praça XV, o Palácio Cruz e Sousa e o centro histórico.'
  },
  {
    id: 'praca_xv_florianopolis',
    name: 'Praça XV de Novembro',
    category: 'Cultura',
    city: 'Florianópolis',
    address: 'Praça XV de Novembro, s/n - Centro, Florianópolis - SC',
    hours: 'Diariamente: acesso livre',
    price: 'Gratuito',
    rating: '4.5 ★ (12.5k avaliações)',
    popularRank: 9,
    route: 9,
    image: 'imagens/praca_xv_floripa.jpg',
    summary: 'Uma das praças mais tradicionais de Florianópolis, cercada por importantes edifícios históricos e pela famosa figueira centenária.',
    description: 'A Praça XV de Novembro é um dos principais espaços históricos de Florianópolis. Localizada no coração do centro, reúne árvores, jardins e monumentos e é marcada pela presença da tradicional figueira centenária. Ao seu redor estão atrações como a Catedral Metropolitana e o Palácio Cruz e Sousa.',
    tip: 'Caminhe ao redor da praça e observe a grande figueira, um dos símbolos mais tradicionais do centro de Florianópolis.'
  },
  {
    id: 'manguezal_itacorubi',
    name: 'Manguezal do Itacorubi',
    category: 'Natureza',
    city: 'Florianópolis',
    address: 'Itacorubi - Florianópolis, SC',
    hours: 'Área de preservação: acesso conforme locais autorizados',
    price: 'Gratuito',
    rating: '—',
    popularRank: 10,
    route: 10,
    image: 'imagens/manguezal_itacorubi.jpeg',
    summary: 'Importante área de manguezal localizada próxima ao centro de Florianópolis e fundamental para a conservação do ecossistema costeiro.',
    description: 'O Manguezal do Itacorubi é uma das principais áreas de mangue de Florianópolis. O ecossistema desempenha importante papel ambiental na proteção da costa, na reprodução de espécies e na manutenção da biodiversidade. A região também ajuda a preservar uma paisagem natural em meio à expansão urbana da cidade.',
    tip: 'Respeite as áreas de preservação e procure observar a fauna e a vegetação sem sair dos locais permitidos.'
  },
  {
    id: 'praia_cacupe',
    name: 'Praia de Cacupé',
    category: 'Praia',
    city: 'Florianópolis',
    address: 'Estrada Haroldo Soares Glavan, 2003-1941 - Cacupé, Florianópolis - SC',
    hours: 'Diariamente: acesso livre',
    price: 'Gratuito',
    rating: '4.6 ★ (248 avaliações)',
    popularRank: 11,
    route: 11,
    image: 'imagens/praia_cacupe.jpeg',
    summary: 'Praia tranquila de águas calmas na Baía Norte, com vista para o centro de Florianópolis e para as pontes da cidade.',
    description: 'A Praia de Cacupé possui aproximadamente 650 metros de extensão e apresenta águas tranquilas, características de uma praia de baía. Cercada por vegetação e com vista para o centro de Florianópolis e para o continente, é uma opção interessante para quem busca tranquilidade e belas paisagens.',
    tip: 'Combine Cacupé com Santo Antônio de Lisboa, principalmente no final da tarde para apreciar o pôr do sol.'
  },
  {
    id: 'freguesia_santo_antonio_lisboa',
    name: 'Freguesia de Santo Antônio de Lisboa',
    category: 'Cultura',
    city: 'Florianópolis',
    address: 'R. Quinze de Novembro, 140 - Santo Antônio de Lisboa, Florianópolis - SC',
    hours: 'Diariamente: acesso livre',
    price: 'Gratuito',
    rating: '4.7 ★',
    popularRank: 12,
    route: 12,
    image: 'imagens/santo_antonio_lisboa.jpeg',
    summary: 'Uma das comunidades mais antigas de Florianópolis, conhecida pelo casario açoriano, artesanato, gastronomia e pôr do sol.',
    description: 'Santo Antônio de Lisboa preserva uma das mais importantes paisagens culturais de Florianópolis, marcada pela arquitetura colonial e pela forte influência açoriana. A região possui restaurantes especializados em frutos do mar e ostras, ateliês, artesanato e uma orla tranquila com belas vistas da Baía Norte.',
    tip: 'Chegue no final da tarde para caminhar pela orla e apreciar o famoso pôr do sol de Santo Antônio de Lisboa.'
  },
  {
    id: 'praia_jurere_internacional',
    name: 'Praia de Jurerê Internacional',
    category: 'Praia',
    city: 'Florianópolis',
    address: 'Jurerê Internacional - Florianópolis, SC',
    hours: 'Diariamente: acesso livre',
    price: 'Gratuito',
    rating: '4.7 ★',
    popularRank: 13,
    route: 13,
    image: 'imagens/jurere_internacional.jpg',
    summary: 'Praia de águas calmas e infraestrutura sofisticada, conhecida pelos beach clubs, hotéis, restaurantes e pelo ambiente de alto padrão.',
    description: 'Jurerê Internacional é um dos destinos mais conhecidos do litoral de Florianópolis. A praia possui águas geralmente calmas e uma extensa faixa de areia, enquanto o bairro oferece hotéis, restaurantes, beach clubs e infraestrutura voltada ao turismo. A região é especialmente movimentada durante o verão.',
    tip: 'Durante a alta temporada, chegue cedo para encontrar estacionamento e aproveitar a praia com mais tranquilidade.'
  },
  {
    id: 'morro_lagoa_conceicao',
    name: 'Mirante do Morro da Lagoa da Conceição',
    category: 'Mirante',
    city: 'Florianópolis',
    address: 'Rodovia Admar Gonzaga - Lagoa da Conceição, Florianópolis - SC',
    hours: 'Diariamente: acesso livre',
    price: 'Gratuito',
    rating: '4.7 ★',
    popularRank: 14,
    route: 14,
    image: 'imagens/morro_lagoa_conceicao.jpg',
    summary: 'Mirante localizado na subida do Morro da Lagoa, com vista panorâmica para a Lagoa da Conceição e parte da Ilha de Santa Catarina.',
    description: 'O Mirante do Morro da Lagoa da Conceição é uma das paradas mais tradicionais para contemplar a paisagem de Florianópolis. Do alto é possível observar a Lagoa da Conceição, os morros, áreas urbanizadas e diferentes regiões da Ilha de Santa Catarina.',
    tip: 'Pare no mirante durante o trajeto entre o centro e a Lagoa da Conceição e aproveite para registrar uma fotografia panorâmica.'
  },
  {
    id: 'praia_joaquina',
    name: 'Praia da Joaquina',
    category: 'Praia',
    city: 'Florianópolis',
    address: 'Av. Pref. Acácio Garibaldi São Thiago, s/n - Praia da Joaquina, Florianópolis - SC',
    hours: 'Diariamente: acesso livre',
    price: 'Gratuito',
    rating: '4.7 ★ (31.3k avaliações)',
    popularRank: 15,
    route: 15,
    image: 'imagens/praia_joaquina.jpeg',
    summary: 'Uma das praias mais famosas de Florianópolis, conhecida pelas ondas, pelo surfe, pelas dunas e pelo nascer do sol.',
    description: 'A Praia da Joaquina possui cerca de 3 quilômetros de extensão e é reconhecida internacionalmente por suas condições favoráveis ao surfe. Além da praia, a região possui grandes dunas utilizadas para sandboard e áreas de interesse arqueológico nas proximidades.',
    tip: 'Chegue cedo para assistir ao nascer do sol e, se gostar de aventura, experimente o sandboard nas dunas.'
  },
  {
    id: 'praia_campeche',
    name: 'Praia do Campeche',
    category: 'Praia',
    city: 'Florianópolis',
    address: 'R. Jerônimo Venâncio das Chagas - Campeche, Florianópolis - SC',
    hours: 'Diariamente: acesso livre',
    price: 'Gratuito',
    rating: '4.7 ★ (9.2k avaliações)',
    popularRank: 16,
    route: 16,
    image: 'imagens/praia_campeche.jpeg',
    summary: 'Extensa praia do sul da Ilha, procurada por surfistas, praticantes de kitesurfe e visitantes que desejam conhecer a Ilha do Campeche.',
    description: 'A Praia do Campeche possui aproximadamente 3,5 quilômetros de extensão e combina faixa de areia, mar aberto e paisagens naturais. É bastante procurada para esportes aquáticos e também funciona como um dos principais pontos de embarque para a Ilha do Campeche.',
    tip: 'Se quiser visitar a Ilha do Campeche, reserve o passeio com antecedência e confira as condições de navegação.'
  },
  {
    id: 'mirante_morro_das_pedras',
    name: 'Mirante do Morro das Pedras',
    category: 'Mirante',
    city: 'Florianópolis',
    address: 'Rod. Francisco Thomaz dos Santos - Morro das Pedras, Florianópolis - SC',
    hours: 'Diariamente: acesso livre',
    price: 'Gratuito',
    rating: '4.7 ★',
    popularRank: 17,
    route: 17,
    image: 'imagens/mirante_morro_das_pedras.jpeg',
    summary: 'Mirante com vista panorâmica para o litoral sul de Florianópolis, especialmente para a Praia do Morro das Pedras e a Lagoa do Peri.',
    description: 'O Mirante do Morro das Pedras proporciona uma das paisagens mais bonitas do sul da Ilha de Santa Catarina. Do alto, o visitante pode observar a faixa litorânea, o mar aberto, áreas de vegetação e a Lagoa do Peri, criando um cenário ideal para contemplação e fotografia.',
    tip: 'Visite em dias de céu limpo e aproveite o percurso para conhecer também a Praia do Morro das Pedras e a Lagoa do Peri.'
  },
  {
    id: 'ribeirao_da_ilha',
    name: 'Ribeirão da Ilha',
    category: 'Cultura',
    city: 'Florianópolis',
    address: 'Rod. Baldicero Filomeno - Ribeirão da Ilha, Florianópolis - SC',
    hours: 'Diariamente: acesso livre',
    price: 'Gratuito',
    rating: '4.7 ★',
    popularRank: 18,
    route: 18,
    image: 'imagens/ribeirao_da_ilha.jpg',
    summary: 'Histórico distrito açoriano conhecido pelo casario tradicional, pela produção de ostras e pela gastronomia à base de frutos do mar.',
    description: 'Ribeirão da Ilha é uma das regiões mais tradicionais de Florianópolis e preserva fortes características da colonização açoriana. O distrito combina casario histórico, igrejas, praias tranquilas, restaurantes especializados em frutos do mar e uma das principais áreas produtoras de ostras do Brasil.',
    tip: 'Reserve algumas horas para conhecer o centro histórico e experimentar ostras frescas em um dos restaurantes da região.'
  },
  {
    id: 'praia_itaguacu',
    name: 'Praia de Itaguaçu',
    category: 'Praia',
    city: 'Florianópolis',
    address: 'Itaguaçu - Coqueiros, Florianópolis - SC',
    hours: 'Diariamente: acesso livre',
    price: 'Gratuito',
    rating: '4.8 ★ (346 avaliações)',
    popularRank: 19,
    route: 19,
    image: 'imagens/praia_itaguacu.jpeg',
    summary: 'Praia tranquila da região continental de Florianópolis, cercada por formações rochosas e com belas vistas para a Baía Sul.',
    description: 'A Praia de Itaguaçu está localizada no bairro de Coqueiros e é conhecida pela paisagem formada por pequenas ilhas e rochas que surgem nas águas da baía. A região possui restaurantes, bares e espaços para contemplação, sendo uma opção agradável para um passeio no continente.',
    tip: 'Combine Itaguaçu com a Praia de Bom Abrigo e o Parque de Coqueiros para fazer um roteiro pela região continental.'
  },
  {
    id: 'praia_bom_abrigo',
    name: 'Praia de Bom Abrigo',
    category: 'Praia',
    city: 'Florianópolis',
    address: 'Bom Abrigo - Florianópolis, SC',
    hours: 'Diariamente: acesso livre',
    price: 'Gratuito',
    rating: '4.8 ★ (234 avaliações)',
    popularRank: 20,
    route: 20,
    image: 'imagens/praia_bom_abrigo.jpg',
    summary: 'Pequena praia de águas tranquilas localizada na região continental de Florianópolis.',
    description: 'A Praia de Bom Abrigo é uma das praias mais tranquilas da região continental de Florianópolis. Protegida pelas águas da Baía Sul, apresenta ambiente agradável para contemplação e lazer e está próxima de outras atrações de Coqueiros e Itaguaçu.',
    tip: 'Aproveite para caminhar pela orla e conhecer os restaurantes da região de Coqueiros.'
  },
  {
    id: 'coqueiros_florianopolis',
    name: 'Coqueiros',
    category: 'Atração',
    city: 'Florianópolis',
    address: 'Coqueiros - Florianópolis, SC',
    hours: 'Diariamente: acesso livre',
    price: 'Gratuito',
    rating: '4.7 ★',
    popularRank: 21,
    route: 21,
    image: 'imagens/coqueiros_floripa.jpeg',
    summary: 'Tradicional bairro da região continental de Florianópolis, conhecido pelas praias de baía, gastronomia e pelo Parque de Coqueiros.',
    description: 'Coqueiros é uma das regiões mais agradáveis da parte continental de Florianópolis. O bairro reúne praias como Itaguaçu e Bom Abrigo, restaurantes, áreas de lazer e o Parque de Coqueiros, formando um roteiro interessante para quem deseja conhecer uma face diferente da capital catarinense.',
    tip: 'Faça o passeio no final da tarde e combine Parque de Coqueiros, Itaguaçu e Bom Abrigo.'
  }
];
