/* ==========================================================================
   Brusque - Tourist Spot Data
   Consumed by ../assets/app.js
   ========================================================================== */

window.CITY_NAME = 'Parobé';

window.CITY_DATA = [
  {
    id: 'panificio_real',
    name: 'Panifício Real',
    category: 'Gastronomia',
    address: 'Av. Patrício Lima, 1616 - Tubarão SC',
    hours: 'Segunda a sábado: 06:30h às 21:00h | Domingo: 14:00h às 21:00h',
    price: '$$',
    rating: '4.6 ★ (1k+ avaliações)',
    popularRank: 1,
    route: 1,
    image: 'imagens/padaria.jpg',
    summary: 'Tradicional padaria e confeitaria de Tubarão SC, conhecida pela variedade de pães, doces, salgados e opções para café.',
    description: 'O Panifício Real é uma tradicional padaria e confeitaria de Tubarão, localizada na Avenida Patrício Lima. O estabelecimento oferece uma grande variedade de pães, doces, salgados, cafés e produtos de confeitaria, sendo uma opção bastante procurada tanto pelos moradores quanto por visitantes que passam pela cidade.',
    tip: 'Uma boa opção para uma parada durante a viagem, especialmente no início da manhã, quando há grande variedade de pães e produtos frescos.'
  },
  {
    id: 'casa_da_colonia',
    name: 'Casa DaColônia',
    category: 'Gastronomia',
    address: 'RS-030, esquina com RS 474 - Sto. A. Patrulha RS',
    hours: 'Segunda a quinta: 07:00h às 19:30h | Sexta: 07:00h às 20:30h | Sábado: 07:00h às 20:00h | Domingo: 07:00h às 20:30h',
    price: '$$ - $$$',
    rating: '4.6 ★ (7.3k avaliações)',
    popularRank: 2,
    route: 2,
    image: 'imagens/casa-da-colonia.jpg',
    summary: 'Tradicional parada gastronômica com produtos coloniais em Santo Antônio da Patrulha RS.',
    description: 'A Casa DaColônia foi inaugurada em 1998 e se tornou uma tradicional parada gastronômica de Santo Antônio da Patrulha. O espaço reúne loja de produtos coloniais, produção de pães e cucas, cafeteria, lanches e restaurante. Entre as especialidades estão o Café Açoriano e o Sonho de Santo Antônio da Patrulha, preparados com receitas ligadas às origens açorianas da família proprietária.',
    tip: 'É uma excelente parada para quem está viajando pela região. Reserve um tempo para conhecer a loja de produtos coloniais além de fazer uma refeição ou tomar um café.'
  },
  {
    id: 'loja_vulcabras_parobe',
    name: 'Loja Vulcabras',
    category: 'Compras',
    address: 'R. Dr. Legendre, 34 - Sala 3 - Parobé RS',
    hours: 'Segunda a sexta: 09h00 às 18h00 | Sábado: 09h00 às 15h30',
    price: '$$',
    rating: '4.6 ★ (326 avaliações)',
    popularRank: 3,
    route: 3,
    image: 'imagens/loja-vulcabras.png',
    summary: 'Loja de fábrica em Parobé RS, com calçados de marcas do grupo Vulcabras e vendas direto da região produtora.',
    description: 'A Loja Vulcabras de Parobé está localizada no centro da cidade e oferece aos visitantes a oportunidade de encontrar calçados das marcas pertencentes ao grupo Vulcabras. Parobé possui forte tradição na indústria calçadista do Rio Grande do Sul, tornando a visita interessante para quem busca produtos diretamente na região de fabricação.',
    tip: 'Confira as promoções e a disponibilidade de tamanhos antes da viagem, especialmente se estiver procurando modelos específicos.'
  },
  {
    id: 'loja_bottero_parobe',
    name: 'Loja Bottero',
    category: 'Compras',
    address: 'Av. Artuino Arsand, 428 - Parobé RS',
    hours: 'Segunda a quinta: 09h00 às 12h30 e 13h30 às 18h30 | Sexta: 09h00 às 18h30 | Sábado: 08h00 às 12h00',
    price: '$$',
    rating: '4.7 ★ (264 avaliações)',
    popularRank: 4,
    route: 4,
    image: 'imagens/loja-bottero.png',
    summary: 'Loja da fábrica da Bottero em Parobé RS, oferecendo calçados da tradicional marca gaúcha.',
    description: 'A Loja da Fábrica da Bottero em Parobé é uma parada interessante para quem aprecia calçados produzidos no Rio Grande do Sul. Localizada na Avenida Artuino Arsand, a loja oferece produtos da marca Bottero e está inserida em uma cidade reconhecida pela tradição e importância da indústria calçadista.',
    tip: 'Vale a pena conferir os modelos em promoção e aproveitar a visita a outras lojas de fábrica de Parobé.'
  },
  {
    id: 'katarze_picada_cafe',
    name: 'Katarze - Outlet de Calçados',
    category: 'Compras',
    address: 'BR-116, 4151 - Picada Café RS',
    hours: 'Segunda a sexta: 09h00 às 11h30 e 12h30 às 18h00 | Sábado e domingo: 09h00 às 18h00',
    price: '$$',
    rating: '4.4 ★ (111 avaliações)',
    popularRank: 5,
    route: 5,
    image: 'imagens/katarze.jpg',
    summary: 'Outlet de calçados às margens da BR-116, em Picada Café RS, com marcas como Coca-Cola e Street.',
    description: 'A Katarze é um outlet de calçados situado às margens da BR-116, em Picada Café RS. O estabelecimento oferece diferentes opções de calçados e funciona como uma parada de compras para quem percorre a Rota Romântica e a Serra Gaúcha. Sua localização estratégica facilita a visita durante deslocamentos entre as cidades da região.',
    tip: 'Como fica às margens da BR-116, é uma parada prática durante uma viagem pela Rota Romântica. Reserve alguns minutos para conferir as promoções.'
  },
  {
    id: 'schmitt_tricot',
    name: 'Schmitt Tricot - Picada Café',
    category: 'Compras',
    address: 'Rod. Presidente Getúlio Vargas, 2297 - Picada Café RS',
    hours: 'Segunda a sexta: 08h00 às 18h00 | Sábado e domingo: 08h30 às 19h00',
    price: '$$',
    rating: '4.6 ★ (694 avaliações)',
    popularRank: 6,
    route: 6,
    image: 'imagens/schmitt-tricot.png',
    summary: 'Loja tradicional de roupas de inverno e tricô em Picada Café RS, com ampla variedade de peças para diferentes estilos.',
    description: 'A Schmitt Tricot é uma tradicional loja de roupas localizada no centro de Picada Café RS. Especializada em peças de inverno e tricô, oferece uma ampla variedade de roupas e produtos para quem visita a Serra Gaúcha. O estabelecimento é uma opção bastante procurada por turistas interessados em moda de inverno e produtos típicos da região.',
    tip: 'Se estiver viajando durante o inverno, reserve um tempo para conferir as peças de tricô e roupas de inverno disponíveis na loja.'
  },
  {
    id: 'cidade_zaandam',
    name: 'Cidade Zaandam',
    category: 'Cultura',
    address: 'Av. 15 de Novembro, 1057 - Nova Petrópolis RS',
    hours: 'Segunda a sexta: 11h00 às 22h00 | Sábado e feriados: 09h00 às 00h00 | Domingo: 09h00 às 22h00',
    price: '$$ - $$$',
    rating: '4.5 ★ (5.2k avaliações)',
    popularRank: 7,
    route: 7,
    image: 'imagens/cidade-zaandam.png',
    summary: 'Complexo temático inspirado na Holanda que reproduz elementos arquitetônicos e culturais da cidade holandesa de Zaandam.',
    description: 'A Cidade Zaandam é uma atração temática de Nova Petrópolis RS, criada por uma família descendente de holandeses com o objetivo de homenagear as colônias holandesas no Brasil. O espaço reproduz elementos de uma cidade típica da Holanda e combina arquitetura temática, gastronomia e experiências inspiradas na cultura holandesa.',
    tip: 'Aproveite a visita para conhecer a gastronomia do local e fotografar as construções inspiradas na arquitetura holandesa.'
  },
  {
    id: 'praca_das_flores',
    name: 'Praça das Flores',
    category: 'Natureza',
    address: 'Rua Rui Barbosa - Nova Petrópolis RS',
    hours: 'Aberto 24 horas',
    price: 'Gratuito',
    rating: '4.8 ★',
    popularRank: 8,
    route: 8,
    image: 'imagens/praca-das-flores.jpg',
    summary: 'Uma das áreas mais charmosas de Nova Petrópolis RS, cercada por jardins floridos e localizada no coração da cidade.',
    description: 'A Praça das Flores é um dos principais espaços públicos e cartões-postais de Nova Petrópolis RS. Localizada no centro da cidade, destaca-se pelos jardins bem cuidados, flores e áreas de convivência. O espaço faz parte do conjunto turístico central e é ideal para caminhadas, descanso e fotografias, além de estar próximo de outros atrativos e estabelecimentos da cidade.',
    tip: 'Combine a visita com a Rua Coberta e outros atrativos do centro de Nova Petrópolis. Na primavera, as flores tornam o cenário especialmente bonito.'
  },
  {
    id: 'dakota_flagship_store',
    name: 'Dakota Flagship Store',
    category: 'Compras',
    address: 'Av. 15 de Novembro, 3667 - Nova Petrópolis RS',
    hours: 'Diariamente: 09h00 às 19h00',
    price: '$$',
    rating: '4.1 ★ (3.7k avaliações)',
    popularRank: 9,
    route: 9,
    image: 'imagens/dakota-flagship.jpg',
    summary: 'Loja flagship e outlet da Dakota em Nova Petrópolis RS, com grande variedade de calçados femininos da marca.',
    description: 'A Dakota Flagship Store está localizada na Avenida 15 de Novembro, em Nova Petrópolis RS, e oferece uma ampla variedade de calçados da marca. O estabelecimento funciona como uma importante parada de compras para visitantes que percorrem a região da Serra Gaúcha e a Rota Romântica, especialmente para quem procura produtos da indústria calçadista gaúcha.',
    tip: 'Confira a seção de ofertas e promoções, que pode ser especialmente interessante para quem procura calçados da marca por preços diferenciados.'
  },
  {
    id: 'mukli_alfajores',
    name: 'Mukli Alfajores',
    category: 'Gastronomia',
    address: 'RS-235, km 14, nº 3003 - Nova Petrópolis RS',
    hours: 'Diariamente: 09h00 às 18h30',
    price: '$$',
    rating: '4.8 ★ (4k avaliações)',
    popularRank: 11,
    route: 11,
    image: 'imagens/mukli-alfajores.jpg',
    summary: 'Cafeteria e loja de fábrica especializada em alfajores de inspiração uruguaia, com doce de leite, chocolate e produtos artesanais.',
    description: 'A Mukli Alfajores é uma empresa familiar de origem uruguaia instalada em Nova Petrópolis RS. Sua especialidade são os alfajores produzidos com doce de leite uruguaio, chocolate da Serra Gaúcha e uma massa artesanal com especiarias. A loja de fábrica na Linha Brasil conta também com cafeteria, estacionamento, acessibilidade e área externa pet friendly.',
    tip: 'Além de experimentar os alfajores, aproveite a cafeteria e leve algumas unidades para continuar a experiência depois da viagem.'
  },
  {
    id: 'cervejaria_edelbrau',
    name: 'Cervejaria Edelbrau',
    category: 'Gastronomia',
    address: 'Av. 15 de Novembro, 4024 - Nova Petrópolis RS',
    hours: 'Diariamente: 09h00 às 17h00',
    price: '$$',
    rating: '4.5 ★ (2k avaliações)',
    popularRank: 10,
    route: 10,
    image: 'imagens/cervejaria-edelbrau.png',
    summary: 'Cervejaria artesanal com loja em Nova Petropólis RS, gastronomia e experiência interativa dedicada à cultura da cerveja.',
    description: 'A Cervejaria Edelbrau oferece uma experiência interativa sobre a produção e a cultura da cerveja artesanal, com espaços temáticos, degustações e vista para a fábrica. O local também conta com loja e opções gastronômicas.',
    tip: 'Reserve um tempo para fazer a Experiência Edelbrau e aproveitar as degustações de diferentes estilos de cerveja.'
  }
];
