/* ==========================================================================
   Gramado - Tourist Spot Data
   Consumed by ../assets/app.js
   ========================================================================== */

window.CITY_NAME = 'Gramado';

window.CITY_DATA = [
  {
    id: 'lago_negro',
    name: 'Lago Negro',
    category: 'Natureza',
    address: 'Rua A. J. Renner - Planalto',
    hours: 'Acesso 24h | Pedalinhos: 08:30h às 18h',
    price: 'Gratuito | Pedalinhos: Consultar valor cobrado',
    rating: '4.8 ★ (25k+ avaliações)',
    popularRank: 1,
    route: 1,
    image: 'imagens/lago_negro.jpg',
    summary: 'Um dos parques mais famosos de Gramado, cercado por araucárias, flores e um lago de águas escuras.',
    description: 'O Lago Negro é um dos cartões-postais naturais de Gramado. O parque é conhecido pela paisagem formada por árvores, jardins e pelo lago, onde os tradicionais pedalinhos são uma das atividades mais procuradas pelos visitantes.',
    tip: 'Reserve pelo menos uma hora para caminhar ao redor do lago e aproveitar os diferentes ângulos para fotografias.'
  },
  {
    id: 'belvedere_vale_quilombos',
    name: 'Belvedere Vale dos Quilombos',
    category: 'Paisagem',
    address: 'Av. das Hortênsias, 2536 - Vila Suica',
    hours: 'Acesso 24h',
    price: 'Gratuito',
    rating: '4.6 (6k+ avaliações)',
    popularRank: 21,
    route: 2,
    image: 'imagens/belvedere_vale_quilombos.png',
    summary: 'Mirante com vista panorâmica para o Vale do Quilombo, localizado na estrada entre Gramado e Canela.',
    description: 'O Belvedere Vale dos Quilombos é uma parada tradicional para contemplar a paisagem serrana. Situado em uma área elevada da Avenida das Hortênsias, proporciona uma vista ampla do vale e da vegetação característica da região.',
    tip: 'Visite pela manhã ou em dias de céu aberto para aumentar as chances de encontrar boa visibilidade do vale.'
  },
  {
    id: 'carrossel_casa_da_montanha',
    name: 'Carrossel Casa da Montanha',
    category: 'Atração',
    address: 'Av. Borges de Medeiros, 3166 - Centro',
    hours: 'Diariamente: acesso livre',
    price: 'Gratuito',
    rating: '4.6 ★ (4k avaliações)',
    popularRank: 14,
    route: 3,
    image: 'imagens/carrossel_casa_montanha.png',
    summary: 'Charmoso carrossel inspirado nos tradicionais brinquedos de parques europeus.',
    description: 'O Carrossel Casa da Montanha é um dos cenários mais fotografados de Gramado. Com decoração delicada e temática alpina, tornou-se uma parada tradicional para famílias e visitantes que circulam pela Avenida Borges de Medeiros.',
    tip: 'Aproveite para fotografar o carrossel, especialmente no período noturno, quando a iluminação deixa o cenário ainda mais encantador.'
  },
  {
    id: 'mcdonalds_harry_potter',
    name: 'Fachada Loja do McDonald’s',
    category: 'Atração',
    address: 'Av. Borges de Medeiros, 3088 - Centro',
    hours: 'Diariamente: 08:30h às 23h',
    price: '$ - $$',
    rating: '4.1 ★ (11.5k avaliações)',
    popularRank: 22,
    route: 4,
    image: 'imagens/mcdonalds_harry_potter.jpg',
    summary: 'Unidade do McDonald’s bastante fotografada pelos visitantes por sua ambientação associada ao imaginário de Harry Potter.',
    description: 'A unidade do McDonald’s localizada na Avenida Borges de Medeiros tornou-se uma parada popular entre turistas que percorrem o centro de Gramado. O estabelecimento combina o serviço tradicional da rede com uma fachada e elementos visuais que chamam a atenção dos visitantes.',
    tip: 'Inclua a parada durante um passeio pela Borges de Medeiros e aproveite para fotografar a fachada.'
  },
  {
    id: 'jardim_encantado_florybal',
    name: 'Jardim Florybal',
    category: 'Atração',
    address: 'Av. Borges de Medeiros, 2771 - Centro',
    hours: 'Diariamente: 09h às 22:30h',
    price: 'Gratuito',
    rating: '4.7 ★ (580+ avaliações)',
    popularRank: 19,
    route: 5,
    image: 'imagens/jardim_florybal.png',
    summary: 'Espaço temático e gratuito da Florybal com jardins, personagens fantásticos, dinossauros e ambientes coloridos.',
    description: 'O Jardim Encantado Florybal é uma pequena atração temática localizada junto à loja de chocolates da marca. O espaço reúne elementos lúdicos, personagens, réplicas de dinossauros, áreas para crianças e diversos cenários para fotografias.',
    tip: 'É uma boa parada para famílias com crianças e para quem procura cenários gratuitos e fotogênicos no centro de Gramado.'
  },
  {
    id: 'casa_velha_bruxa',
    name: 'Casa da Velha Bruxa',
    category: 'Gastronomia',
    address: 'Av. Borges de Medeiros, 2738 - Centro',
    hours: 'Diariamente: 13h às 23h',
    price: '$$ - $$$',
    rating: '4.6 ★ (7.4k  avaliações)',
    popularRank: 12,
    route: 6,
    image: 'imagens/velha-bruxa.jpg',
    summary: 'Tradicional casa de lanches de Gramado, famosa por seus chocolates quentes, crepes, waffles e sobremesas.',
    description: 'Tradicional ponto gastronômico de Gramado, a Casa da Velha Bruxa funciona desde 1978 e se destaca pelo ambiente acolhedor e temática inspirada no universo das bruxas. Localizada na Avenida Borges de Medeiros, próxima à Rua Coberta e ao Palácio dos Festivais, é conhecida por seus lanches, crepes, waffles, sobremesas e pelo tradicional chocolate quente. É uma parada bastante procurada por visitantes que desejam fazer uma pausa durante o passeio pelo centro de Gramado.',
    tip: 'Uma boa pedida para uma pausa durante o passeio pelo centro de Gramado, especialmente para experimentar o tradicional chocolate quente e as sobremesas da casa.'
  },
  {
    id: 'largo_da_borges',
    name: 'Largo da Borges',
    category: 'Compras',
    address: 'Av. Borges de Medeiros, 2727 - Centro',
    hours: 'Diariamente: Gastronomia - 10h às 23h | Lojas e quiosques: 10h às 19:30h',
    price: 'Gratuito',
    rating: '4.6 ★ (4.7k avaliações)',
    popularRank: 11,
    route: 7,
    image: 'imagens/largo_da_borges.png',
    summary: 'Complexo comercial e gastronômico no coração de Gramado, cercado por lojas, cafés, restaurantes e atrações turísticas.',
    description: 'O Largo da Borges está localizado em uma das áreas mais movimentadas do centro de Gramado. O espaço reúne comércio, gastronomia e arquitetura charmosa, sendo uma parada conveniente durante o passeio pela Avenida Borges de Medeiros.',
    tip: 'Combine a visita com a Rua Coberta, o Palácio dos Festivais e a Igreja São Pedro, todos próximos.'
  },
  {
    id: 'calcada_da_fama_gramado',
    name: 'Calçada da Fama de Gramado',
    category: 'Atração',
    address: 'Av. Borges de Medeiros - em frente ao Palácio dos Festivais - Centro',
    hours: 'Diariamente: acesso livre',
    price: 'Gratuito',
    rating: '3.9 ★ (21 avaliações)',
    popularRank: 8,
    route: 8,
    image: 'imagens/calcada_fama_gramado.jpg',
    summary: 'Calçada que reúne mãos e assinaturas de artistas e personalidades ligadas ao cinema e à televisão brasileira.',
    description: 'A Calçada da Fama de Gramado está localizada em frente ao Palácio dos Festivais e ao longo da Avenida Borges de Medeiros. A iniciativa está relacionada ao tradicional Festival de Cinema de Gramado e recebe novas homenagens ao longo das edições do festival.',
    tip: 'Observe as placas com as mãos e assinaturas dos artistas e aproveite para fotografá-las durante o passeio pelo centro.'
  },
  {
    id: 'palacio_dos_festivais',
    name: 'Palácio dos Festivais',
    category: 'Entretenimento',
    address: 'Av. Borges de Medeiros, 2697 - Centro',
    hours: 'Bilheteria: consultar programação | Sessões: conforme calendário',
    price: 'Consultar programação',
    rating: '4.6 ★ (1.4k avaliações)',
    popularRank: 7,
    route: 9,
    image: 'imagens/palacio_festivais.jpg',
    summary: 'Principal símbolo do Festival de Cinema de Gramado e um dos edifícios culturais mais conhecidos da cidade.',
    description: 'O Palácio dos Festivais é o tradicional palco do Festival de Cinema de Gramado e um dos pontos culturais mais importantes da Serra Gaúcha. O prédio também abriga atividades relacionadas ao cinema e, durante o Natal Luz, recebe atrações especiais.',
    tip: 'Visite a fachada e o Caminho das Estrelas em frente ao prédio. Durante o Natal Luz, confira também a programação especial do local.'
  },
  {
    id: 'termo_metro_gramado',
    name: 'Termômetro de Gramado',
    category: 'Atração',
    address: 'Av. Borges de Medeiros, 679 - Centro',
    hours: 'Diariamente: acesso livre',
    price: 'Gratuito',
    rating: '4.9 ★ (88 avaliações)',
    popularRank: 16,
    route: 10,
    image: 'imagens/termometro_gramado_centro.png',
    summary: 'Tradicional relógio-termômetro urbano que se tornou um dos elementos característicos da paisagem de Gramado.',
    description: 'Os relógios e termômetros de estilo alpino fazem parte da identidade visual de Gramado. Esses equipamentos são procurados pelos turistas principalmente durante os períodos de frio, quando a temperatura registrada se transforma em uma lembrança da viagem.',
    tip: 'Fotografe o equipamento quando a temperatura estiver baixa para registrar uma lembrança típica da Serra Gaúcha.'
  },
  {
    id: 'fonte_amor_eterno',
    name: 'Fonte do Amor Eterno',
    category: 'Atração',
    address: 'Av. Borges de Medeiros, 2659 - ao lado da Igreja São Pedro - Centro',
    hours: 'Diariamente: acesso livre',
    price: 'Gratuito',
    rating: '4.7 ★ (23k avaliações)',
    popularRank: 10,
    route: 11,
    image: 'imagens/fonte_amor_eterno.jpg',
    summary: 'Fonte romântica onde visitantes colocam cadeados para simbolizar amor, amizade ou uma lembrança especial.',
    description: 'Localizada ao lado da Igreja Matriz São Pedro, a Fonte do Amor Eterno tornou-se um dos pontos mais românticos de Gramado. O espaço é conhecido pelos cadeados coloridos colocados pelos visitantes como símbolo de amor e afeto.',
    tip: 'A fonte é uma parada rápida e combina perfeitamente com a visita à Igreja São Pedro e ao centro de Gramado.'
  },  
  {
    id: 'igreja_matriz_sao_pedro',
    name: 'Igreja Matriz São Pedro',
    category: 'Atração',
    address: 'Av. Borges de Medeiros, 2659 - Centro',
    hours: 'Seg a Sáb: conforme programação | Dom: conforme missas',
    price: 'Gratuito',
    rating: '4.9 ★ (5.6k avaliações)',
    popularRank: 3,
    route: 12,
    image: 'imagens/igreja_sao_pedro_gramado.png',
    summary: 'Igreja construída em pedra basáltica, considerada um dos principais cartões-postais do centro de Gramado.',
    description: 'A Igreja Matriz São Pedro é um dos símbolos arquitetônicos e religiosos de Gramado. Sua construção em pedra basáltica e os vitrais que decoram o interior fazem dela uma das paradas mais tradicionais para quem visita o centro da cidade.',
    tip: 'Visite também à noite, quando a iluminação externa destaca a arquitetura de pedra da igreja.'
  },
  {
    id: 'rua_coberta_gramado',
    name: 'Rua Coberta Gramado',
    category: 'Atração',
    address: 'Rua Madre Verônica, 30 - Centro',
    hours: 'Acesso 24h',
    price: 'Gratuito',
    rating: '4.7 ★ (9.3k avaliações)',
    popularRank: 2,
    route: 13,
    image: 'imagens/rua_coberta_gramado.jpg',
    summary: 'Uma das atrações mais tradicionais do centro de Gramado, com restaurantes, cafés, lojas e eventos durante todo o ano.',
    description: 'A Rua Coberta é um dos principais pontos de encontro de Gramado. Protegida por uma estrutura coberta e decorada com plantas e iluminação, concentra restaurantes, cafés, lojas e apresentações culturais, especialmente durante eventos e épocas festivas.',
    tip: 'Visite durante o dia e novamente à noite para apreciar a iluminação e o movimento dos restaurantes.'
  },
  {
    id: 'praca_major_nicoletti',
    name: 'Praça Major Nicoletti',
    category: 'Paisagem',
    address: 'Av. Borges de Medeiros - Centro',
    hours: 'Acesso 24h',
    price: 'Gratuito',
    rating: '4.8 ★ (231 avaliações)',
    popularRank: 6,
    route: 14,
    image: 'imagens/praca_major_nicoletti.jpg',
    summary: 'Charmosa praça no centro de Gramado, próxima à Rua Coberta, à Igreja São Pedro e ao Palácio dos Festivais.',
    description: 'A Praça Major Nicoletti é um dos espaços tradicionais do centro de Gramado. Cercada por estabelecimentos comerciais e atrações turísticas, oferece bancos, jardins e um agradável espaço para uma pausa durante o passeio.',
    tip: 'Use a praça como ponto de descanso durante o roteiro a pé pelo centro histórico e turístico.'
  },
  {
    id: 'cuco_da_borges',
    name: 'Relógio Cuco',
    category: 'Atração',
    address: 'Av. Borges de Medeiros - Centro',
    hours: 'Acesso 24h',
    price: 'Gratuito',
    rating: '4.6 ★ (56 avaliações)',
    popularRank: 15,
    route: 15,
    image: 'imagens/cuco_da_borges.png',
    summary: 'Relógio de estilo europeu que chama a atenção dos visitantes pela arquitetura temática.',
    description: 'O Cuco da Borges é um dos elementos decorativos que ajudam a reforçar a atmosfera europeia do centro de Gramado. O relógio tornou-se um cenário procurado para fotografias durante os passeios pela Avenida Borges de Medeiros.',
    tip: 'Inclua o Cuco da Borges no roteiro a pé pelo centro e aproveite para fotografar os detalhes da construção.'
  },
  {
    id: 'fonte_perfumada',
    name: 'Fonte de Perfume Amati',
    category: 'Atração',
    address: 'Av. Borges de Medeiros, 2388 - Centro',
    hours: 'Acesso 24h',
    price: 'Gratuito',
    rating: '4.5 ★ (24 avaliações)',
    popularRank: 17,
    route: 16,
    image: 'imagens/fonte_perfumada.jpg',
    summary: 'Fonte aromática localizada em frente à loja Amati, conhecida pelo perfume que se espalha pelo entorno.',
    description: 'A Fonte Perfumada é uma atração curiosa localizada na Avenida Borges de Medeiros. O aroma associado à fonte chama a atenção de quem passa pela região e complementa a experiência sensorial proporcionada pelas lojas de perfumes e cosméticos do entorno.',
    tip: 'Passe pelo local durante uma caminhada pela Borges de Medeiros e aproveite para conhecer os produtos aromáticos da região.'
  },
  {
    id: 'royal_trudel',
    name: 'Royal Trudel',
    category: 'Gastronomia',
    address: 'Av. Borges de Medeiros, 2300 - Loja 10 - Centro',
    hours: 'Diariamente: 10h às 22h',
    price: '$ - $$',
    rating: '4.6 ★ (3k+ avaliações)',
    popularRank: 18,
    route: 17,
    image: 'imagens/royal_trudel.jpg',
    summary: 'Doceria especializada no tradicional Trdelník, doce de origem europeia servido com diferentes recheios e coberturas.',
    description: 'A Royal Trudel tornou-se uma das docerias mais conhecidas de Gramado por apresentar o tradicional Trdelník, doce de massa assada em espiral, servido com recheios, cremes e acompanhamentos variados.',
    tip: 'Experimente o Trudel servido quente e escolha um recheio de chocolate, doce de leite ou frutas.'
  },
  {
    id: 'hard_rock_cafe_gramado',
    name: 'Hard Rock Cafe Gramado',
    category: 'Gastronomia',
    address: 'Rua Wilma Dinnebier, 180 - Centro',
    hours: 'Dom a Qui: 12h às 23h | Sex e Sáb: 12h às 00h',
    price: '$ - $$',
    rating: '4.5 ★ (16k avaliações)',
    popularRank: 13,
    route: 18,
    image: 'imagens/hard_rock_gramado.png',
    summary: 'Restaurante e bar temático inspirado na história do rock, com decoração repleta de objetos musicais e apresentações especiais.',
    description: 'O Hard Rock Cafe Gramado combina gastronomia, música e entretenimento em um ambiente temático. A unidade reúne itens relacionados a grandes nomes do rock, além de hambúrgueres, pratos internacionais, bebidas e loja de produtos oficiais.',
    tip: 'Reserve um tempo para observar a coleção de objetos musicais e confira a programação de música ao vivo.'
  },
  {
    id: 'rua_torta_gramado',
    name: 'Rua Torta',
    category: 'Atração',
    address: 'Rua Emílio Sorgetz, 1 - Centro',
    hours: 'Acesso 24h',
    price: 'Gratuito',
    rating: '4.6 ★ (9k+ avaliações)',
    popularRank: 4,
    route: 19,
    image: 'imagens/rua_torta.png',
    summary: 'Rua sinuosa e arborizada, inspirada na famosa Lombard Street, de San Francisco, e um dos locais mais fotografados.',
    description: 'A Rua Emílio Sorgetz, conhecida popularmente como Rua Torta, ganhou fama por seu traçado sinuoso, jardins e flores. O cenário é especialmente procurado para fotografias e fica próximo ao centro turístico de Gramado.',
    tip: 'Caminhe por toda a extensão da rua e fotografe de diferentes ângulos para destacar seu formato sinuoso.'
  },
  {
    id: 'hortensias_garden',
    name: 'Hortênsias Garden',
    category: 'Atração',
    address: 'Rua Emílio Sorgetz, 42 - Centro',
    hours: 'Seg à Sáb: 09h às 20h | Dom: 09h às 18h',
    price: 'Serviços/ Ensaios Fotográficos - Consultar Valores.',
    rating: '4.8 ★ (118 avaliações)',
    popularRank: 20,
    route: 20,
    image: 'imagens/hortensias_garden.jpg',
    summary: 'Jardim temático e cenário fotográfico a céu aberto localizado junto à famosa Rua Torta de Gramado.',
    description: 'O Hortênsias Garden é um espaço ao ar livre criado para proporcionar experiências em meio à natureza e a cenários cuidadosamente decorados. Localizado na Rua Torta, um dos pontos mais conhecidos do centro de Gramado, reúne jardins, flores, esculturas e diferentes ambientes preparados especialmente para fotografias. O espaço combina o charme da arquitetura e do paisagismo da Serra Gaúcha com cenários instagramáveis, sendo uma opção interessante para casais, famílias e visitantes que desejam registrar momentos especiais durante o passeio pela região central.',
    tip: 'Combine a visita ao Hortênsias Garden com a Rua Torta e outras atrações do centro de Gramado. O local é especialmente interessante para quem gosta de fotografia e pode render boas fotos em diferentes cenários.'
  },
  {
    id: 'praca_das_etnias',
    name: 'Praça das Etnias',
    category: 'Atração',
    address: 'Av. Borges de Medeiros, 1848 - Centro',
    hours: 'Acesso 24h',
    price: 'Gratuito',
    rating: '4.7 ★ (19k avaliações)',
    popularRank: 9,
    route: 21,
    image: 'imagens/praca_das_etnias.jpg',
    summary: 'A Praça das Etnias é um espaço cultural que homenageia as origens italiana, alemã e portuguesa de Gramado.',
    description: 'A Praça das Etnias reúne construções que representam diferentes povos responsáveis pela formação de Gramado. O espaço abriga a Casa do Colono, fornos de pedra, produtos coloniais, artesanato e ambientes que valorizam as tradições dos imigrantes.',
    tip: 'Experimente os pães e cucas preparados nos fornos de pedra e, se possível, visite a praça aos sábados durante a feira de produtos coloniais.'
  },
  {
    id: 'lago_joaquina_rita_bier',
    name: 'Lago Joaquina Rita Bier',
    category: 'Natureza',
    address: 'Rua Leopoldo Rosenfeld, 919 - Planalto',
    hours: 'Acesso 24h',
    price: 'Gratuito',
    rating: '4.7 ★ (432 avaliações)',
    popularRank: 5,
    route: 22,
    image: 'imagens/lago_joaquina_rita_bier.png',
    summary: 'Lago artificial cercado por jardins, araucárias e áreas de contemplação, próximo ao centro de Gramado.',
    description: 'O Lago Joaquina Rita Bier é um dos cenários mais tradicionais de Gramado. Cercado por vegetação e áreas ajardinadas, o lago oferece um ambiente tranquilo para caminhadas, contemplação e fotografias. Durante o Natal Luz, também se transforma em cenário para apresentações especiais.',
    tip: 'Durante o Natal Luz, confira a programação relacionada ao lago, que pode receber espetáculos e iluminação especial.'
  },
  {
    id: 'fondue_chateau_platanos',
    name: 'Fondue Chateau dos Plátanos',
    category: 'Gastronomia',
    address: 'Rua João Alfredo Schneider, 607 - Planalto',
    hours: 'Seg, Qua a Sáb: 18:30h às 22h | Dom: 11:30h às 14h e 18:30h às 22h | Ter: fechado.',
    price: '$ - $$',
    rating: '4.4 ★ (5.4k avaliações)',
    popularRank: 23,
    route: 23,
    image: 'imagens/chateau_platanos.jpg',
    summary: 'Especializado em fondue, uma das experiências gastronômicas mais procuradas na Serra Gaúcha.',
    description: 'O Chateau dos Plátanos oferece uma experiência gastronômica inspirada na tradição do fondue. O restaurante possui ambiente aconchegante e é uma opção bastante procurada por casais e famílias durante as noites frias de Gramado.',
    tip: 'No inverno, faça reserva antecipada, principalmente para jantar nos finais de semana.'
  },  
  {
    id: 'forneria_corleone',
    name: 'Forneria Corleone',
    category: 'Gastronomia',
    address: 'Vita Boulevard - Rua São Pedro, 757 - Sala 20 - Centro',
    hours: 'Ter a Dom: 19h às 23h',
    price: '$ - $$',
    rating: '4.9 ★ (1.3k avaliações)',
    popularRank: 24,
    route: 24,
    image: 'imagens/forneria_corleone.png',
    summary: 'Pizzaria artesanal com ambiente temático e proposta gastronômica inspirada na tradição italiana.',
    description: 'A Forneria Corleone é uma pizzaria localizada no Vita Boulevard, no centro de Gramado. O estabelecimento combina pizzas artesanais com ambiente temático e uma proposta voltada à experiência gastronômica.',
    tip: 'É uma boa opção para jantar depois de um passeio noturno pelo centro de Gramado.'
  },
  {
    id: 'natal_luz_gramado_2026',
    name: 'Natal Luz de Gramado 2026',
    category: 'Natal',
    address: 'Diversos locais - Gramado RS',
    hours: '22/10/2026 a 17/01/2027',
    price: 'Atrações gratuitas e espetáculos pagos',
    rating: '4.3 ★ (4k avaliações)',
    popularRank: 26,
    route: 25,
    image: 'imagens/natal_luz_gramado_2026.jpg',
    summary: 'Grande temporada natalina que transforma Gramado em um cenário iluminado com espetáculos, desfiles e atrações gratuitas.',
    description: 'O 41º Natal Luz de Gramado acontece de 22 de outubro de 2026 a 17 de janeiro de 2027. A programação inclui atrações gratuitas, Vila de Natal, Show de Acendimento, apresentações na Rua Coberta, Parada de Natal e espetáculos como Nativitaten, O Grande Desfile de Natal, O Brilho do Natal e Natal Luz In Concert.',
    tip: 'Para aproveitar melhor o evento, consulte o calendário oficial antes da viagem e reserve antecipadamente os espetáculos pagos.'
  },
];
